
### get all messages
GET http://localhost:3000/messages

### get messages by to
GET http://localhost:3000/messages?to=avi


###
POST http://localhost:3000/messages
Content-Type: application/json

{
    "from": "avi",
    "to": "shalom", 
    "message": "I am glad to hear so"
}



### 
DELETE http://localhost:3000/messages?to=avi