# Generated by Django 5.2.3 on 2025-06-15 12:14

from django.db import migrations

from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command('loaddata', "initial_data.json")


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures)
    ]
